//AUTOGENERATED FILE FROM png2asset
// Conversion args: Oak.png -spr8x8 -sw 16 -sh 16

#ifndef METASPRITE_Oak_H
#define METASPRITE_Oak_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Oak_TILE_ORIGIN 0
#define Oak_TILE_W 8
#define Oak_TILE_H 8
#define Oak_WIDTH 16
#define Oak_HEIGHT 16
#define Oak_TILE_COUNT 3
#define Oak_PALETTE_COUNT 1
#define Oak_COLORS_PER_PALETTE 4
#define Oak_TOTAL_COLORS 4
#define Oak_PIVOT_X 8
#define Oak_PIVOT_Y 8
#define Oak_PIVOT_W 16
#define Oak_PIVOT_H 16
extern const metasprite_t* const Oak_metasprites[1];

BANKREF_EXTERN(Oak)

extern const palette_color_t Oak_palettes[4];
extern const uint8_t Oak_tiles[48];

#endif
